### ISSUE TITLE
Wrapper components are not always properly instantiated

### ISSUE THREAD

**Issue by avermeer** [ulgaal/react-infotip#1]
Hello,

When the wrapper component is a function and not a class, it does not get properly instantiated (for instance, `Pinnable`).

This is because the code calls a `createWrapper `utility function. 

I think that `React.createElement` should probably be called directly instead.

If that sounds good, then please assign this incident: I can provide a PR with this fix.

Kind regards,
Alexandre Vermeerbergen

**Comment by ulgaal** [comment]
Hi Alexandre,
I agree with you. Could you please provide a PR to fix this ?

**Comment by avermeer** [comment]
Hi @ulgaal,

My pleasure. 

I have a question: what is react-infotip release cycle? what is the cycle to get new path/minor/major releases pushed to npm repository?

Kind regards,
Alexandre
